version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  web:
    env_file: .env
    build: ./web
    container_name: 'kickstarter_web'
    command: ./entrypoint.sh
    volumes:
      - ./web:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data:
  redis_data: